### ISSUE TITLE
[Exam] Template for Midterm Exam

### ISSUE THREAD

**Issue by lamduynguyen** [JonghyeokPark/SWE3003-41-and-ECE5605-41#16]
In the exam notification, there is only word template.

Is this possible to upload the latex template, too?
I mostly use latex to prepare assignments answer.

Thank you.

**Comment by JonghyeokPark** [comment]
Sure, You can.

**Comment by lamduynguyen** [comment]
Please upload the latex template. Thanks!

**Comment by JonghyeokPark** [comment]
I thought you already have the latex template, I modify the notice please refer to the attached file.

**Comment by lamduynguyen** [comment]
Many thanks for your help! I will close this issue.
