### ISSUE TITLE
Where to submit the final report and the presentation

### ISSUE THREAD

**Issue by lamduynguyen** [JonghyeokPark/SWE3003-41-and-ECE5605-41#21]
Hi TA, please answer the above question!

Also, what is the format of the final report, as well as the requirements for the presentation!

**Comment by JonghyeokPark** [comment]
@duynguyen-ori75 

1. You don't have to submit the presentation file (must attend the presentation 5/31) 
2. As the assignment guide document says, latex format (paper format)

**Comment by lamduynguyen** [comment]
@JonghyeokPark do you mean that we have to submit in VLDB format?

Sorry, can you send me the assignment guide? Thanks!

**Comment by JonghyeokPark** [comment]
@duynguyen-ori75 Please check the file "0. Term project topics (Spring 2021)" in week 9.

You should prepare a conference-style report on your project with maximum length of 6pages (either in Usenix format (https://www.usenix.org/conferences/author-resources/paper-templates) or IEEE CS format (http://icde2017.sdsc.edu/submission-guidelines) ) Your report should introduce and motivate the problem your project addresses, describe related work in the area, discuss the elements of your solution, and present results that measure the behavior, performance, or functionality of your system (hopefully with comparisons to other related systems as appropriate.

**Comment by lamduynguyen** [comment]
Many thanks!

Will I present it in the webex, or should I record a video for that?
