### ISSUE TITLE
[Lecture] About lecture video

### ISSUE THREAD

**Issue by ChaeSeoyoung** [JonghyeokPark/SWE3003-41-and-ECE5605-41#3]
As I listen to the lecture video, I cannot see the letter because of the resolution.
I'd like to ask you improve in the next lecture. Thank you.

안녕하세요, 데베개를 수강하는 학생입니다. 강의를 들을 때, 화질이 좋지 않아 화면의 SQL Plus 글자가 보이지 않습니다. (아래 사진 참조)
다음 강의 때는 개선되었으면 좋겠어 이렇게 문의드립니다. 감사합니다.

채서영 드림

![image](https://user-images.githubusercontent.com/55826320/109444022-896d2980-7a7f-11eb-958b-cc5c94c5bca8.png)

**Comment by JonghyeokPark** [comment]
We'd like to apologize for the low video quality. We will convey this feedback to Professor for providing better video quality. 

해당 피드백을 반영하여 수강하는데 불편이 없도록 교수님께 전달하겠습니다.
